name: Release build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest # explicitly use 20.04, see commit 428c40018f
    timeout-minutes: 30
    strategy:
      fail-fast: false
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: >-
        WORKAROUND: Fetch tags that points to the revisions
        checked-out(actions/checkout#1467)
      run: |-
        git fetch --tags --force

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Set environment variable from secret
      run: echo "SWARM_KEY=${{ secrets.SWARM_KEY }}" >> $GITHUB_ENV

    - name: Build
      run: |
        make cross qemu-wrapper vm win-gvproxy win-sshproxy
        mv bin/gvproxy.exe bin/gvproxy-windowsgui.exe

    - uses: actions/upload-artifact@v4
      with:
        name: gvisor-tap-vsock-binaries
        path: bin/*

    - name: Create release on github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          gh release create --draft --generate-notes --verify-tag ${{github.ref_name}}
          cd bin
          sha256sum * >> sha256sums
          gh release upload ${{github.ref_name}} *
